<a href="https://colab.research.google.com/github/mr-ayush-agrawal/DL_Notebooks/blob/main/PyTorch/1-Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Foundation
Sclaer and tensor

In [1]:
import torch as pt

In [2]:
pt.__version__

'2.5.1+cu121'

In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [4]:
scaler = pt.tensor(4)
scaler

tensor(4)

In [5]:
vec = pt.tensor([5, 4, 1])
vec

tensor([5, 4, 1])

In [6]:
vec.ndim

1

In [7]:
vec.size()

torch.Size([3])

In [8]:
mat = pt.tensor([[1, 2],
                 [3, 4]])
mat

tensor([[1, 2],
        [3, 4]])

In [9]:
mat.size()

torch.Size([2, 2])

In [10]:
mat.ndim

2

In [11]:
mat[1]

tensor([3, 4])

ndim >= 3 => Tensor

In [12]:
random_tensor = pt.rand(2, 5)
random_tensor

tensor([[0.4192, 0.2105, 0.7488, 0.6926, 0.9973],
        [0.5196, 0.7633, 0.2772, 0.9352, 0.3388]])

In [13]:
zten = pt.zeros(2, 1)
zten

tensor([[0.],
        [0.]])

In [14]:
# we can also use like
zten = pt.arange(1, 5)
_ = pt.ones_like(zten)
_

tensor([1, 1, 1, 1])

### Tensor Data Types
3 issues which are generally into Pt and DL
1. Tensor not right dtype
1. Tensor not right shape
1. Tensor not on right device

In [15]:
ten = pt.tensor([3., 5., 12],
                dtype = pt.float16,
                device = None,
                requires_grad = False)


ten.dtype, ten.device, ten.requires_grad

(torch.float16, device(type='cpu'), False)

In [16]:
f32ten = pt.tensor([1, 35, 2], dtype = pt.float)
f32ten.dtype

torch.float32

In [17]:
res =  ten * f32ten
res.dtype

torch.float32

In [18]:
m1 = pt.tensor([[1, 2, 3], [2, 3, 5]])
m2 = pt.tensor([[1, 3], [3, 5], [5, 7]])

m1.shape, m2.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [19]:
# Element wise mulitplication
m1 * m1

tensor([[ 1,  4,  9],
        [ 4,  9, 25]])

In [20]:
# Matrix multipication
pt.matmul(m1, m2)

tensor([[22, 34],
        [36, 56]])

In [21]:
pt.matmul(m2, m1)

tensor([[ 7, 11, 18],
        [13, 21, 34],
        [19, 31, 50]])

In [22]:
pt.matmul(m1, m1.T)

tensor([[14, 23],
        [23, 38]])

In [23]:
%%time
m1 @ m2

CPU times: user 1.03 ms, sys: 6 µs, total: 1.04 ms
Wall time: 2.25 ms


tensor([[22, 34],
        [36, 56]])

In [24]:
%%time
# mm is same as the matmul its short form of the matmul
pt.mm(m1, m2)

CPU times: user 0 ns, sys: 626 µs, total: 626 µs
Wall time: 617 µs


tensor([[22, 34],
        [36, 56]])

### Mean

- This only works for the float type

In [25]:
pt.min(m1), pt.max(m1)

(tensor(1), tensor(5))

In [26]:
pt.mean(m1.type(pt.float)), pt.mean(m1.type(pt.float), axis = 1), pt.mean(m1.type(pt.float), axis = 0)

(tensor(2.6667), tensor([2.0000, 3.3333]), tensor([1.5000, 2.5000, 4.0000]))

In [27]:
m1

tensor([[1, 2, 3],
        [2, 3, 5]])

In [28]:
m1.type(pt.float).mean(axis = 1)

tensor([2.0000, 3.3333])

In [29]:
%%time
m1.sum()

CPU times: user 567 µs, sys: 0 ns, total: 567 µs
Wall time: 448 µs


tensor(16)

In [30]:
%%time
sum = 0
for x in m1:
    for y in x:
        sum += y
sum

CPU times: user 2.04 ms, sys: 8 µs, total: 2.05 ms
Wall time: 6.33 ms


tensor(16)

In [31]:
x = pt.rand(10)
x

tensor([0.0689, 0.3822, 0.7799, 0.9750, 0.4374, 0.0818, 0.2431, 0.0821, 0.8493,
        0.4920])

In [32]:
x.argmin(), x.argmax()

(tensor(0), tensor(3))

In [33]:
pt.cuda.is_available()

False

In [37]:
tensor = pt.tensor([1, 4, 2, 5, 6], device = 'cpu')
tensor, tensor.device

(tensor([1, 4, 2, 5, 6]), device(type='cpu'))

In [39]:
type(tensor.cpu().numpy())

numpy.ndarray