<a href="https://colab.research.google.com/github/mr-ayush-agrawal/DL_Notebooks/blob/main/PyTorch/1-Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Foundation
Sclaer and tensor

In [4]:
import torch as pt

In [5]:
pt.__version__

'2.5.1+cu121'

In [6]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [8]:
scaler = pt.tensor(4)
scaler

tensor(4)

In [10]:
vec = pt.tensor([5, 4, 1])
vec

tensor([5, 4, 1])

In [11]:
vec.ndim

1

In [14]:
vec.size()

torch.Size([3])

In [15]:
mat = pt.tensor([[1, 2],
                 [3, 4]])
mat

tensor([[1, 2],
        [3, 4]])

In [16]:
mat.size()

torch.Size([2, 2])

In [18]:
mat.ndim

2

In [19]:
mat[1]

tensor([3, 4])

ndim >= 3 => Tensor